import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  cardContainer: {
    backgroundColor: '#2976BF',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  titleLabel: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    color: '#E0F2FE',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
  },
  roomCodeText: {
    fontSize: 32,
    fontWeight: '800',
    fontFamily: 'Poppins-ExtraBold',
    color: '#FFFFFF',
    letterSpacing: 1.5,
  },
  copyButton: {
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 8,
  },
  statusText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    color: '#FFFFFF',
    marginBottom: 20,
    opacity: 0.9,
    textAlign: 'center',
  },
  avatarsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    marginBottom: 20,
  },
  avatarWrapper: {
    alignItems: 'center',
    width: 80,
  },
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 8,
  },
  avatarImage: {
    width: 48,
    height: 48,
  },
  avatarLabel: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  gacoSection: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    color: '#E0F2FE',
    marginBottom: 8,
  },
  gacoSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 90,
    marginBottom: 12,
  },
  gacoDisplayCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
  },
  gacoDisplaySide: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    opacity: 0.35,
  },
  gacoImageCenter: {
    width: 60,
    height: 60,
  },
  gacoImageSide: {
    width: 40,
    height: 40,
  },
  gacoName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginTop: 4,
  },
  confirmButton: {
    backgroundColor: '#000000',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 4,
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
  },
  confirmedGacoContainer: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 12,
  },
  confirmedGacoText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 10,
  },
  readyButton: {
    backgroundColor: '#059669',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  readyButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
    letterSpacing: 0.5,
  },
  readyBadge: {
    backgroundColor: 'rgba(5, 150, 105, 0.25)',
    borderWidth: 1.5,
    borderColor: '#34D399',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 20,
  },
  readyBadgeText: {
    color: '#34D399',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
  },
  waitingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
    width: '100%',
    marginBottom: 8,
  },
  waitingText: {
    color: '#FFDE43',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 10,
    flex: 1,
    textAlign: 'center',
  },
  cancelButton: {
    marginTop: 10,
    paddingVertical: 6,
  },
  cancelButtonText: {
    color: '#E0F2FE',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
    textDecorationLine: 'underline',
  },
});
