import { StyleSheet } from 'react-native';
import { vw, vh } from '../../utils/responsive';

const styles = StyleSheet.create({
  modalOverlay: {
    position: 'absolute',
    top: -500,
    bottom: -500,
    left: -500,
    right: -500,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 30,
  },
  modalContainer: {
    width: vw(99),
    backgroundColor: '#1E1E2E',
    borderRadius: 24,
    padding: 25,
    borderWidth: 2,
    borderColor: '#3E3E5E',
    shadowColor: '#BD00FF',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
    alignItems: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 15,

    borderBottomColor: '#784B23',
    paddingBottom: 10,
  },
  levelBadge: {
    left: -4,
    top: -65,
    paddingHorizontal: 30,
    paddingVertical: 7,
    borderRadius: 8,
    fontWeight: 'bold',
    backgroundColor: '#4E2C0E',
    borderColor: '#784B23',
  },
  badgeEasy: {
    borderWidth: 1.5,
  },
  badgeMedium: {
    borderWidth: 1.5,
  },
  badgeHots: {
    borderWidth: 1.5,
  },
  badgeTextEasy: {

    color: '#FFDE43',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  badgeTextMedium: {
    color: '#FFDE43',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  badgeTextHots: {
    color: '#FFDE43',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  weightBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#4E2C0E',
    borderColor: '#784B23',
    borderWidth: 1.5,
    top: -65,
    right: -3,
  },
  weightBadgeText: {
    color: '#FFDE43',
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
  },
  questionContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0)',
    borderRadius: 12,
    padding: 15,
    width: '75%',
    alignSelf: 'center',

    marginVertical: 10,
  },
  questionText: {
    color: '#FFFFFF',
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
    fontFamily: 'Poppins-Medium',
  },
  textInput: {
    width: '70%',
    backgroundColor: '#2b1401',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#784B23',
    color: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    marginVertical: 10,
    alignSelf: 'center',
    textAlign: 'center',
  },
  nextButton: {
    backgroundColor: '#784B23',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 30,
    marginTop: 15,
    width: '60%',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#4E2C0E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  popupBg: {
    width: vw(95),
    height: vh(72),
    maxHeight: 560,
    borderRadius: 24,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 20,
    paddingTop: 30,
    paddingBottom: 85,
  },
  invisibleSubmitButton: {
    position: 'absolute',
    bottom: 22,
    width: '78%',
    height: 50,
    backgroundColor: 'transparent',
    borderRadius: 14,
    alignSelf: 'center',
  },
  popupBgTransparent: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
    padding: 0,
  },
  popupTimerContainer: {
    backgroundColor: '#4E2C0E',
    borderColor: '#784B23',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 10,
    alignSelf: 'center',
  },
  popupTimerText: {
    color: '#FFDE43',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
});

export default styles;
