import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    marginBottom: 20,
  },
  titleContainer: {
    flex: 1,
    marginLeft: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 15,
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  title: {
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    color: '#333',
  },
  subtitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#555',
  },
  roundText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#007BFF',
    marginTop: 4,
  },
  gameArea: {
    flex: 1,
    marginHorizontal: 20,
    marginBottom: 40,
    position: 'relative',
    backgroundColor: 'transparent',
  },
  columnLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'space-around',
    width: '40%',
  },
  columnRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'space-around',
    width: '40%',
  },
  wordBox: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    borderColor: '#E0E0E0',
    borderWidth: 2,
  },
  wordBoxCompleted: {
    backgroundColor: '#E8F5E9',
    borderColor: '#4CAF50',
    borderWidth: 2,
  },
  wordText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#333',
  },
  wordTextCompleted: {
    color: '#4CAF50',
  },
  snackbarOverlayWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    zIndex: 1000,
  },
  snackbarContainer: {
    padding: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    minHeight: 200,
    justifyContent: 'space-between',
  },
  snackbarTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 22,
    marginBottom: 10,
  },
  snackbarSubtitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
    color: '#D32F2F',
    marginBottom: 2,
  },
  snackbarText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#D32F2F',
    marginBottom: 5,
    lineHeight: 20,
  },
  snackbarButton: {
    backgroundColor: '#000',
    borderRadius: 30,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 20,
  },
  snackbarButtonText: {
    fontFamily: 'Poppins-Bold',
    fontSize: 16,
    color: '#FFF',
  }
});
